export const musicbutler = `<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
</head>
<head>
<meta charset="utf-8">
<meta name="x-apple-disable-message-reformatting">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="format-detection" content="telephone=no, date=no, address=no, email=no">
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
<style>td,th,div,p,a,h1,h2,h3,h4,h5,h6{font-family:"Segoe UI",sans-serif;mso-line-height-rule:exactly;}
</style>
<![endif]-->
<style>
@media screen{a[x-apple-data-detectors],#MessageViewBody a{color:inherit!important;text-decoration:none!important;font-size:inherit!important;font-family:inherit!important;font-weight:inherit!important;line-height:inherit!important;}}
@media (max-width:600px){.g{display:block!important;}.g8{margin-top:10px!important;}.q{padding-left:0!important;padding-right:0!important;}.r{padding-left:14px!important;padding-right:14px!important;}.u{padding-top:16px!important;padding-bottom:16px!important;}.s{padding-left:24px!important;padding-right:24px!important;}.skk{padding-top:32px!important;padding-bottom:32px!important;}.e{width:100%!important;}}
</style>
</head>
<body style="margin:0;padding:0;width:100%;word-break:break-word;-webkit-font-smoothing:antialiased;background-color:#64748b;"><div role="article" aria-roledescription="email" aria-label lang="en">
<table style="font-family:-apple-system,'Segoe UI',sans-serif;width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><td align="center" style="background-color:#64748b;" bgcolor="#64748b">
<table class="e" style="width:600px;" width="600" cellpadding="0" cellspacing="0" role="presentation"><tr><td class="skk s" style="padding:48px;text-align:center;" align="center"> <a href="https://www.musicbutler.io"> <img src="https://musicbutler-static.s3.amazonaws.com/logo-email-small.png" width="75" alt="MusicButler logo" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td></tr><tr><td align="center" class="s">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><td class="s" style="background-color:#f1f5f9;border-radius:8px;font-size:16px;line-height:24px;padding:32px 48px;text-align:center;color:#374151;" bgcolor="#f1f5f9" align="center"><p style="font-weight:700;margin:0 0 24px;">Hey leolabs, here's your music drop from MusicButler</p>
<table align="center" class="e" style="margin:0 auto;box-shadow:0 10px 15px -3px rgba(0,0,0,0.1),0 4px 6px -2px rgba(0,0,0,0.05);width:66.666667%;" width="66.666667%" cellpadding="0" cellspacing="0" role="presentation"><tr><td class="u" style="background-color:#27303f;border-radius:8px;padding-top:24px;padding-bottom:24px;" bgcolor="#27303f">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation">  <tr><td style="text-align:center;" align="center"><div> <a href="https://www.musicbutler.io/" style="font-weight:600;font-size:18px;line-height:32px;color:#f1f5f9;text-decoration:none;">10 albums</a></div> <a href="https://www.musicbutler.io/" style="font-size:14px;color:#97a6ba;text-decoration:none;">Yesterday</a>
</td></tr><tr><td style="height:14px;" height="14">
</td></tr> 
                                 <tr><td style="text-align:center;" align="center"><div> <a href="https://www.musicbutler.io/" style="font-weight:600;font-size:18px;line-height:32px;color:#f1f5f9;text-decoration:none;">3 albums</a></div> <a href="https://www.musicbutler.io/" style="font-size:14px;color:#97a6ba;text-decoration:none;">Past Month</a>
</td></tr>  </table>
</td></tr></table><div style="line-height:64px;">&zwnj;</div>
<table align="center" class="e" style="margin:0 auto;width:83.333333%;" width="83.333333%" cellpadding="0" cellspacing="0" role="presentation"> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/4a/ca/82/4aca8227-f234-cdc2-4c7c-32a913658ae7/21UMGIM57038.rgb.jpg/450x450bb.jpeg" width="150" class="e" alt="Two Another' - 'Jump" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Jump</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/1063322932/" style="color:#475569;text-decoration:none;"> Two Another </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/jump-single/1577455116" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/2TgHDF2mvQorYI0uHcCBP4" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Jump Two Another" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is2-ssl.mzstatic.com/image/thumb/Music115/v4/78/45/70/784570c8-aa9e-6572-903e-b17c6341bda5/024543951575_cover.jpg/450x450bb.jpeg" width="150" class="e" alt="goosetaf' - 'Pink Salt" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Pink Salt</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/1240057602/" style="color:#475569;text-decoration:none;"> goosetaf </a> &middot; </span>  <span> <a href="https://www.musicbutler.io/artist-page/974153123/" style="color:#475569;text-decoration:none;"> Ian Ewing </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/pink-salt-single/1577514619" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/2ZgoM4uUC54r2lS3SYqvbF" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Pink Salt Ian Ewing" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/0d/3b/d1/0d3bd1c0-c318-c4e4-5601-75bf554bbb8d/0750122875511_cover.jpg/450x450bb.jpeg" width="150" class="e" alt="FS Green' - 'Reckless Riddim" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Reckless Riddim</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/292343711/" style="color:#475569;text-decoration:none;"> FS Green </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/reckless-riddim-single/1576644178" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/25LPa8GiliMzVZYbt1ZPyg" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Reckless Riddim FS Green" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/a5/55/35/a555353c-6ef9-25e2-bfe1-0a72fd24d60c/21UMGIM41383.rgb.jpg/450x450bb.jpeg" width="150" class="e" alt="Barney Artist' - 'Poems" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Poems</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/907082754/" style="color:#475569;text-decoration:none;"> Barney Artist </a> &middot; </span>  <span> <a href="https://www.musicbutler.io/artist-page/204005534/" style="color:#475569;text-decoration:none;"> Mr Jukes </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/poems-ep/1578545258" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/album/5kNlKqMw2Q0kwpRHrVUHBR" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Poems Mr Jukes" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is5-ssl.mzstatic.com/image/thumb/Music125/v4/0e/d5/6a/0ed56ad3-1aa4-d085-31ff-30a0cc92dce1/17244.jpg/450x450bb.jpeg" width="150" class="e" alt="Cailin Russo' - 'Boxing Underwater (feat. Cailin Russo)" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Boxing Underwater (feat. Cailin Russo)</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/720457796/" style="color:#475569;text-decoration:none;"> Cailin Russo </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/boxing-underwater-feat-cailin-russo-single/1576658138" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/0CCvJ8682h023vVdJ4oYKp" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is4-ssl.mzstatic.com/image/thumb/Music115/v4/bc/87/03/bc87034c-2335-fdc1-6768-e3b506ca1845/810060813133.png/450x450bb.jpeg" width="150" class="e" alt="Excision' - 'Broken Pieces (feat. Monika Santucci)" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Broken Pieces (feat. Monika Santucci)</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/287726822/" style="color:#475569;text-decoration:none;"> Excision </a> &middot; </span>  <span> <a href="https://www.musicbutler.io/artist-page/695232897/" style="color:#475569;text-decoration:none;"> Monika Santucci </a> &middot; </span>  <span> <a href="https://www.musicbutler.io/artist-page/639404644/" style="color:#475569;text-decoration:none;"> Dion Timmer </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/broken-pieces-feat-monika-santucci-single/1579535376" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/7nwVLrbEvFNH5sdPepvHjl" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Broken Pieces (feat. Monika Santucci) Dion Timmer" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/05/40/14/0540143f-a7ff-f760-d015-ef2d2496fb61/1562.jpg/450x450bb.jpeg" width="150" class="e" alt="Damian Lazarus' - 'Don&#39;t Be Afraid (feat. Jungle) [Damian Lazarus Re-Shape]" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Don&#39;t Be Afraid (feat. Jungle) [Damian Lazarus Re-Shape]</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/303323567/" style="color:#475569;text-decoration:none;"> Damian Lazarus </a> &middot; </span>  <span> <a href="https://www.musicbutler.io/artist-page/1468290871/" style="color:#475569;text-decoration:none;"> Diplo </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/dont-be-afraid-feat-jungle-damian-lazarus-re-shape-single/1578020022" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/7EWPfAIYrVEVEC6oArXZv1" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Don&#39;t Be Afraid (feat. Jungle) [Damian Lazarus Reshape] Diplo" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/52/f4/9d/52f49d7a-d3f9-14ec-b768-4487cc0e791f/5056495206644_1.jpg/450x450bb.jpeg" width="150" class="e" alt="Purity Ring' - 'Soshy" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Soshy</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/461030854/" style="color:#475569;text-decoration:none;"> Purity Ring </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/soshy-single/1577379656" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/77ThGWtKLzRLtcLUxJ8ONd" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Soshy Purity Ring" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/d4/c0/a1/d4c0a107-f12a-6885-7a3e-cfc0b2b520f5/5056495272748_1.jpg/450x450bb.jpeg" width="150" class="e" alt="Tom Tripp' - 'Running" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Running</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/1196058693/" style="color:#475569;text-decoration:none;"> Tom Tripp </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/running-single/1575282243" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/6A6XVBBYqsyPHmKzHJXoTs" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Running Tom Tripp" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is3-ssl.mzstatic.com/image/thumb/Music125/v4/62/7d/78/627d7828-69f1-709b-849b-bf182554ddd1/198001346453.png/450x450bb.jpeg" width="150" class="e" alt="Claude Debussy' - 'Debussy: Generalis Gratia" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 4, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Debussy: Generalis Gratia</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/219163/" style="color:#475569;text-decoration:none;"> Claude Debussy </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/debussy-generalis-gratia/1577107215" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/album/2RpyJiGYpAsp8YmgAymrmX" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is3-ssl.mzstatic.com/image/thumb/Music115/v4/46/57/cd/4657cdef-dace-4a94-bd34-db77e8f83274/196292174069.jpg/450x450bb.jpeg" width="150" class="e" alt="Casper Mágico' - 'Mucho Brillo" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 3, 2021</span> <img src="https://musicbutler-static.s3.amazonaws.com/explicit-img-prod.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"> </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">Mucho Brillo</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/1187043113/" style="color:#475569;text-decoration:none;"> Casper Mágico </a> &middot; </span>  <span> <a href="https://www.musicbutler.io/artist-page/1459265052/" style="color:#475569;text-decoration:none;"> Hozwal </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/mucho-brillo-single/1578922685" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/3REVYw7xBn8zWLDhjpoY2P" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=Mucho Brillo Hozwal" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is2-ssl.mzstatic.com/image/thumb/Music125/v4/1a/c8/95/1ac89507-01f1-04dd-35bf-e6b066105785/cover.jpg/450x450bb.jpeg" width="150" class="e" alt="Upfront MC' - 'No Question" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">Aug. 3, 2021</span> <img src="https://musicbutler-static.s3.amazonaws.com/explicit-img-prod.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"> </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">No Question</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/1004196914/" style="color:#475569;text-decoration:none;"> Upfront MC </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/no-question-single/1579368788" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/track/00kogVFVXAAAuQwX1h8Ppy" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="http://www.amazon.com/gp/search?ie=UTF8&amp;keywords=No Question Upfront MC" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-amazon.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td>  </tr></table></div></th></tr></table>
</td></tr> 
                           <tr><td style="height:32px;" height="32">
</td></tr>  <tr><td style="background-color:#e2e8f0;border-radius:8px;padding-top:14px;padding-bottom:14px;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);" bgcolor="#e2e8f0">
<table style="width:100%;" width="100%" cellpadding="0" cellspacing="0" role="presentation"><tr><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:41.666667%;" width="41.666667%" align="left"><div class="r"> <img src="https://is2-ssl.mzstatic.com/image/thumb/Music115/v4/f1/06/f9/f106f998-6839-9544-6604-42235e374794/195269105945.jpg/450x450bb.jpeg" width="150" class="e" alt="Antonio Vivaldi' - 'The Red Priest: A Portrait of Antonio Vivaldi" style="max-width:100%;line-height:100%;vertical-align:middle;border-radius:4px;border:1px solid #cfd8e3;box-shadow:0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06);"></div></th><th class="e g q" style="font-weight:400;padding-left:14px;padding-right:14px;text-align:left;width:58.333333%;" width="58.333333%" align="left"><div class="r"><div class="g8" style="margin-bottom:10px;vertical-align:middle;"> <span style="font-size:10px;color:#475569;text-transform:uppercase;">July 28, 2021</span>  </div><h2 style="font-weight:700;font-size:14px;line-height:16px;margin:0;color:#27303f;">The Red Priest: A Portrait of Antonio Vivaldi</h2><div style="line-height:20px;">&zwnj;</div><p style="font-size:12px;line-height:14px;margin:0 0 10px;color:#475569;">  <span> <a href="https://www.musicbutler.io/artist-page/242604/" style="color:#475569;text-decoration:none;"> Antonio Vivaldi </a></span>  </p>
<table cellpadding="0" cellspacing="0" role="presentation"><tr>  <td style="padding-right:16px;"> <a href="https://geo.music.apple.com/il/album/the-red-priest-a-portrait-of-antonio-vivaldi/1579569653" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-apple.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           <td style="padding-right:16px;"> <a href="https://open.spotify.com/album/0Bgke3zyvl35dl6ScAZjNP" style="text-decoration:none;"> <img src="https://musicbutler-static.s3.amazonaws.com/fa-spotify.png" width="16" style="border:0;max-width:100%;line-height:100%;vertical-align:middle;"></a>
</td> 
                                           </tr></table></div></th></tr></table>
</td></tr>  </table>
</td></tr><tr><td style="height:32px;" height="32">
</td></tr><tr><td style="text-align:center;" align="center"> <a href="https://www.musicbutler.io/users/email-unsubscribe/97acb15e-9e2d-480e-9c5e-f6733e719279/" style="font-size:12px;color:#ffffff;text-decoration:underline;">Unsubscribe</a>
</td></tr><tr><td style="height:32px;" height="32">
</td></tr></table>
</td></tr></table>
</td></tr></table></div>
<img width="1px" height="1px" alt="" src="http://email.mg.musicbutler.io/o/eJxNjssOgyAQRb9GdpJx5DEsWJTa_geIWBKsCeqif1-66-7kJOfmRmu0EFGxbBFwAAI50ChH4gN39BzBmMmoh3P329QJ2Fa-XUeew3WWpfK8s5fVQaLHWSSjQhKUVNLojULQs1oCRVZtWfYO3V_ZpporPhx8rys7bfS5fPr6Phr_jvRAPcjYxBdrdDBE"></body>
</html>`;
